export const screens = [
  "MAIN",
  "RECORD",
  "CHOP",
  "PROGRAM",
  "STEP",
  "PERFORMANCE",
  "MIX",
  "DISK",
  "SETTINGS",
  "PAD_PLAY",
  "UTILITY_16_LEVELS",
  "UTILITY_TRACK_MUTE",
  "UTILITY_PAD_MUTE",
  "UTILITY_NEXT_SEQ",
  "UTILITY_NOTE_REPEAT",
  "COUNT_IN",
  "GO_TO",
  "ERASE",
  "UNDO",
  "SEQUENCE_EDIT",
  "SONG",
  "TIMING_CORRECT",
  "TIME_SIG_WINDOW",
  "BAR_EDITOR",
  "FX",
  "FX_SEND_WINDOW",
  "SAMPLE_EDIT_WINDOW",
  "SAMPLE_KEEP_RETRY",
] as const;

export type ScreenId = (typeof screens)[number];
